language: shell
os: windows
matrix:
  fast_finish: true
  include:   
#    - name: "Windows WSL1"
#      before_install:
        #- curl -L -o ubuntu-1804.zip https://aka.ms/wsl-ubuntu-1804
        #- powershell.exe -NoProfile -Command "Expand-Archive -Path ubuntu-1804.zip -DestinationPath Ubuntu"
        #- Ubuntu/ubuntu1804.exe install --root
        #- choco uninstall -y mingw wsl
#        - choco install wsl-ubuntu-1804
#      install:
#        - wsl sudo apt update
#        - wsl sudo DEBIAN_FRONTEND=noninteractive apt dist-upgrade -y
#        - wsl sudo DEBIAN_FRONTEND=noninteractive apt install -y python3-pip
#        - wsl sudo pip3 install --upgrade pip
#      before_script:
#        - wsl pip3 --version
#      script:
#        - wsl ls -lah //usr/local/lib/python3.6/dist-packages/
#        - MSYS_NO_PATHCONV=1 wsl ls -lah /usr/local/lib/python3.6/dist-packages/
    - name: "Python 3.6 on Windows"
      os: windows
      language: shell
      env:
#        - PATH="/c/Python36:/c/Python36/Scripts:/c/Program Files (x86)/keystone/bin/:$PATH"
#      before_install:
#        - choco install python --version=3.6.8
#        - python -m pip install --upgrade pip
#      install:
#        - pip install 'capstone>=4.0.1' 'pefile>=2019.4.18' 'python-registry>=1.3.1' 'unicorn>=1.0.2rc1'
#        - git clone https://github.com/keystone-engine/keystone
#        - cd keystone
#        - mkdir build
#        - cd build
#        - cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64 & ..\nmake-dll.bat'
#        - cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64 & ..\nmake-lib.bat && nmake install'
#        - cd ../bindings/python
#        - python setup.py install
#        - cd $TRAVIS_HOME/build/chfl4gs/qiling
#        - python setup.py install
#      before_script:
#        - mkdir -p rootfs/x8664_windows/dlls
#        - mkdir -p rootfs/x86_windows/dlls
#        - mkdir registry
#       - cmd.exe /C "ntuser hive C:\Users\Default\NTUSER.DAT"
#        - cp /c/Users/Default/NTUSER.DAT registry/NTUSER.DAT
#        - cmd.exe //c "reg save hklm\system registry/SYSTEM"
#        - cmd.exe //c "reg save hklm\security registry/SECURITY"
#        - cmd.exe //c "reg save hklm\software registry/SOFTWARE"
#        - cmd.exe //c "reg save hklm\SAM registry/SAM"
#        - cp -r registry rootfs/x8664_windows/
#        - cp -r registry rootfs/x86_windows/
      script:
        - cmd.exe //C 'dllscollector.bat'
        - ls -lah examples/rootfs/x86_windows/Windows/SysWOW64
        - ls -lah examples/rootfs/x86_windows/Windows/registry
        - ls -lah examples/rootfs/x8664_windows/Windows/System32
        - ls -lah examples/rootfs/x8664_windows/Windows/registry
#        ls -lah registry
#        - grep -E Filename docs/DLLX86.txt | awk {'print $2'} > list32.txt
#        - grep -E Filename docs/DLLX8664.txt | awk {'print $2'} > list64.txt
#        - cd /c/Windows/SysWOW64/ && xargs -a $TRAVIS_HOME/build/chfl4gs/travis-wsl/list32.txt cp -t $TRAVIS_HOME/build/chfl4gs/travis-wsl/rootfs/x86_windows/dlls
#        - cp msvcr120_clr0400.dll $TRAVIS_HOME/build/chfl4gs/travis-wsl/rootfs/x86_windows/dlls/msvcr110.dll
#        - cmd //C "dumpbin /headers /c/Windows/winsxs/amd64_microsoft-windows-printing-xpsprint_31bf3856ad364e35_10.0.17763.194_none_20349c5a971eb293/*.dll"
#        - cmd //C "dumpbin /headers /c/Windows/winsxs/amd64_microsoft-windows-printing-xpsprint_31bf3856ad364e35_10.0.17763.194_none_20349c5a971eb293/*/*.dll"
#        - choco install kb2670838
#        - cmd.exe //c "dism /?"
#        - cmd.exe //C "dism /online /enable-feature /featurename:Printing-XPSServices-Features"
#        - cmd.exe //C "dism /online /Add-Capability /CapabilityName:XPS.Viewer~~~~0.0.1.0"
#        - cat /c/Windows/Logs/DISM/dism.log
        - cmd.exe //C "ServerManagerCmd.exe -query"
        - ls -lah /c/Windows/System32/
#        - ls -laR /c/Windows/SysWOW64/
#        - ls -LaR /c/Windows/System32/
#        - cp downlevel/api-ms-win-crt-stdio-l1-1-0.dll $TRAVIS_HOME/build/chfl4gs/travis-wsl/rootfs/x86_windows/dlls/
#        - cd /c/Windows/System32/ && xargs -a $TRAVIS_HOME/build/chfl4gs/travis-wsl/list64.txt cp -t $TRAVIS_HOME/build/chfl4gs/travis-wsl/rootfs/x8664_windows/dlls
#        - cp vcruntime140d.dll $TRAVIS_HOME/build/chfl4gs/travis-wsl/rootfs/x8664_windows/dlls/
