language: shell
os: windows
matrix:
  fast_finish: true
  include:   
    - name: "Windows WSL1"
      before_install:
        #- curl -L -o ubuntu-1804.zip https://aka.ms/wsl-ubuntu-1804
        #- powershell.exe -NoProfile -Command "Expand-Archive -Path ubuntu-1804.zip -DestinationPath Ubuntu"
        #- Ubuntu/ubuntu1804.exe install --root
        #- choco uninstall -y mingw wsl
        - choco install wsl-ubuntu-1804
      install:
        - wsl sudo apt update
        - wsl sudo DEBIAN_FRONTEND=noninteractive apt dist-upgrade -y
        - wsl sudo DEBIAN_FRONTEND=noninteractive apt install -y python3-pip
        - wsl sudo pip3 install --upgrade pip
      before_script:
        - wsl pip3 --version
      script:
        - wsl ls -lah //usr/local/lib/python3.6/dist-packages/
        - MSYS_NO_PATHCONV=1 wsl ls -lah /usr/local/lib/python3.6/dist-packages/
        - wsl ls -lah //usr/local/lib/python3.6/dist-packages/usr/lib/python3/
        - wsl ls -lah //usr/local/lib/python3.6/
