language: shell
os: windows
matrix:
  fast_finish: true
  include:   
    - name: "Windows WSL1"
      before_install:
        - curl -L -o ubuntu-1804.zip https://aka.ms/wsl-ubuntu-1804
        - powershell.exe -NoProfile -Command "Expand-Archive -Path ubuntu-1804.zip -DestinationPath Ubuntu"
        - Ubuntu/ubuntu1804.exe install --root
      install:
        - wsl sudo apt update
        - wsl sudo DEBIAN_FRONTEND=noninteractive apt dist-upgrade -y
        - wsl sudo DEBIAN_FRONTEND=noninteractive apt install -y python3-pip
        - wsl sudo pip3 install --upgrade pip
      before_script:
        - wsl pip3 --version
      script:
        - wsl `cd \$(python3 -c \"import site; print(site.getsitepackages()[0])\")`
